spring:
  jpa:
#    database: mysql
    database: postgresql
#    database-platform: org.hibernate.dialect.MariaDBDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 1000
        order_inserts: true

  datasource:
#    url: jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:appdb}?autoReconnect=true&useSSL=false
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:appdb}?autoReconnect=true&useSSL=false
    username: ${DB_USER:appuser}
    password: ${DB_PASSWORD:apppwd}
    driver-class-name: org.postgresql.Driver
#    driver-class-name: org.mariadb.jdbc.Driver

#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

#logging:
#  level:
#    org.springframework.transaction: TRACE
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder=TRACE: