spring:
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true

logging.level.root: WARN
logging.level.org.springframework.web: DEBUG
logging.level.org.hibernate: ERROR
logging.level.org.seed: INFO

performance:
  funds:
    weight:
      sharpe: 0.4
      mdd: 0.4
      return-pct: 0.2
